version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"         # maps local port to container's port
    volumes:
      - ./frontend:/src     # optional: live file sync for development
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./config/backend.env

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - ./config/db.env
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data