version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/src
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app
      - ./data:/data
    env_file:
      - ./config/backend.env

  db:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    env_file:
      - ./config/db.env
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: 'dpage/pgadmin4'
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: mypgadminpass
    depends_on:
      - db
